spring:
  application:
    name: home-thermostat-api
  profiles:
    active: development

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:postgresql://localhost:5432/rest_api
    username: postgres
    password: "admin"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: production
server:
  port: 8080
